site_name: Revel Digital for Developers
nav:
    - Home: index.md
    - REST API: rest-api.md
    - Gadgets: gadgets.md
    - Webapps: webapps.md
    - Player API for Windows: windows.md
    - Player API for Android: android.md
theme:
    name: material
    logo: img/logo.png
    features:
    - content.code.copy
markdown_extensions:
    - markdown.extensions.admonition
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.snippets
docs_dir: mkdocs
site_dir: docs
